# Julia 1.6 Interactive Tutorial

## Julia Enviroment
``` $ julia script.jl arg1 arg2 ... ```

- `?` Help Interface
- `;` Shell Command
- `]` Package Manager

## Variables and Math Operations

In [74]:
# Unicode Variable
δ = 0.01 # \delta (TAB)

0.01

In [75]:
# Implied Multiplication
x = 3
println(2x^2 - 3x + 1)

10


In [76]:
# Update Variable
x += 1 # x = x + 1

4

In [77]:
# Test Special Value
isfinite(x), isinf(x), isnan(x)

(true, false, false)

In [78]:
# Chain Comparison
println(2 < x < 5)
println(1 < 2 <= 2 < 3 == 3)

true
true


In [79]:
# Numerical Conversion
Int(1.0) # convert(Int, 1.0) 

1

In [80]:
# Int Division
7 ÷ 3 # div(5, 3)

2

In [81]:
# Decimal Rounding
x = 3.14159
println(round(x))
floor(x); ceil(x); trunc(x);

3.0


## Complex and Rational Numbers

In [82]:
z = 1 + 2im # Complex [im ≡ √(-1)]
println("Re(z) = $(real(z)), Im(z) = $(imag(z))")
println("(Magnitude, Phase Angle) = ($(abs(z)), $(angle(z)))")
println(conj(z))
a, b = 1, 2
z = complex(a, b);

Re(z) = 1, Im(z) = 2
(Magnitude, Phase Angle) = (2.23606797749979, 1.1071487177940904)
1 - 2im


In [83]:
k = 2//3 # Rational
println((numerator(k), denominator(k)))
println(float(3//4)) # Convert Rational -> Float
println(1//3 - 0.33) # Type Promotion

(2, 3)
0.75
0.0033333333333332993


In [11]:
try
    sqrt(-1)
catch e
    println(e)
    sqrt(-1 + 0im)
end

DomainError(-1.0, "sqrt will only return a complex result if called with a complex argument. Try sqrt(Complex(x)).")


0.0 + 1.0im

## Strings (Character Sequences)

In [12]:
println('\u2200') # Unicode Character (∀)
greeting = "Hello" # String Literal
println(length(greeting))
name = "John"
println(name[1], " ", name[end], " ", name[2:3])

∀
5
J n oh


In [13]:
println(greeting * ", " * name) # String Concatenation
println("$greeting, $(name)") # String Interpolation
println(join([greeting, name], ", "))

Hello, John
Hello, John
Hello, John


## Functions (Map: Tuple -> Value)

In [14]:
function f(x, y)
    x + y
end
f(x, y) = x + y # Compact "Assignment Form"
Σ(x, y) = x + y # Unicode Function Name

Σ (generic function with 1 method)

In [15]:
g = f; g(2, 3) # Function Object
1 + 2; +(1, 2) # Operators <=> Functions
(x -> x^2 + 2x - 1)(5) # Anonymous Function

34

In [16]:
# Functional Programming
println(map(round, [1.2, 3.5, 1.7]))
println(filter(x -> x % 2 == 0, [1, 2, 3, 4]))
foreach(print, ['a', 'b'])

[1.0, 4.0, 2.0]
[2, 4]
ab

In [17]:
x = (a=1, b=2) # Named Tuple
x.b

2

In [18]:
function sumdiff(x, y)
    x + y, x - y
end
x, y = sumdiff(10, 5) # Tuple Destructuring

(15, 5)

In [84]:
∘(f, g) = (x...) -> f(g(x...)) # Composition

∘ (generic function with 1 method)

In [19]:
function sum(x, args...) # Variable Arguments
    sum = x
    for arg in args
        sum += arg
    end
    return sum
end
println(sum(1, 2, 3, 4))
A = [5, 6, 7, 8]
println(sum(A...))

10
26


In [20]:
# Optional Arguments
function parse(T::Type{<:Real}, num::String, base::Int=2)
    # Unsupported: Negative, Decimal, Exponential
    res = T(num[end]) - 48
    for i in 1:(length(num) - 1)
        res += T(num[end - i] - 48) * base^i
    end
    return res
end
println(parse(Int, "1101"))
println(parse(Int, "1101", 10))

13
1101


In [21]:
# Keyword Arguments
function parse(T::Type{<:Real}, num::String; base::Int=2)
    # Unsupported: Negative, Decimal, Exponential
    res = T(num[end]) - 48
    for i in 1:(length(num) - 1)
        res += T(num[end - i] - 48) * base^i
    end
    return res
end
println(parse(Int, "1101"))
println(parse(Int, "1101", base=10))

13
1101


In [22]:
# Do-Block Syntax
open("file.txt", "w") do io
    write(io, "Hello World!")
end

12

## Vectorized Functions (Broadcast)

In [23]:
[1, 2, 3] .^ 3; (^).([1, 2, 3], 3) # Vectorized "Dot" Operation
broadcast(x -> x^3, [1, 2, 3]) # Broadcast Operation (<=> "Dot")

3-element Vector{Int64}:
  1
  8
 27

In [24]:
even(x) = x % 2; even.([1, 2, 3]) # Vectorized User-Defined Function
⊗(A, B) = kron(A, B) # Vectorized User-Defined Operator

⊗ (generic function with 1 method)

## Control Flow (If-Else, Loops)

In [25]:
# Compound Expressions (`begin` and `;`)
z = begin
    x = 1
    y = 2
    x + y
end
z = (x = 1; y = 2; x + y)

3

In [26]:
# Conditional Evaluation (`if-elseif-else` and `?:`)
x = 1
if x > 0
    println("$x is positive")
else
    println("$x is negative")
end
x = -1
println(x, x > 0 ? " is positive" : " is negative")

1 is positive
-1 is negative


In [27]:
# Short-Circuit Evaluation (`&&` and `||`)
x > 0 && println("$x is positive") # <cond> 'and then' <statement>
x > 0 || println("$x is negative") # <cond> 'or else' <statement>

-1 is negative


In [28]:
function factorial(n::Int)
    n <= 1 && return 1
    return  n * factorial(n - 1)
end

factorial (generic function with 1 method)

In [29]:
# Repeated Evaluation (`while` and `for`)
i = 1
while i <= 5
    # Body
    i += 1
end
for i = 1:5
    # Body
end
for i in [1, 2, 3] # i ∈ [1, 2, 3]
    # Body
end
for i = 1:2, j = 3:4 # Nested For-Loop
    println((i, j))
end

(1, 3)
(1, 4)
(2, 3)
(2, 4)


In [30]:
# Exception Handling (`try-catch`, `error()`, `throw()`)
struct MyCustomException <: Exception end

In [31]:
f(x) = x >= 0 ? exp(-x) : throw(DomainError())

f (generic function with 2 methods)

In [32]:
f(x) = try
    sqrt(x)
catch
    sqrt(complex(x, 0))
end
println(f(1), ", ", f(-1))
f(x) = x >= 0 ? sqrt(x) : sqrt(complex(x, 0));

1.0, 0.0 + 1.0im


In [33]:
try #= ... =# catch; #= ... =# end
file = open("file.txt")
try #= ... =# finally close(file) end

In [34]:
# Tasks (Coroutines)
function producer(c::Channel)
    put!(c, "Start")
    for n = 1:4
        put!(c, 2n)
    end
    put!(c, "Stop")
end
chnl = Channel(producer)
take!(chnl) # Returns "Start"
take!(chnl); take!(chnl); take!(chnl); take!(chnl) # 2, 4, 6, 8
take!(chnl) # Returns "Stop"
for x in Channel(producer) # Channel - Iterable Object
    println(x)
end

Start
2
4
6
8
Stop


## Variable Scope (Local, Global)

In [35]:
# local x; global x
let w = 10 # Local Scope
    while w < 20
        w += 1
    end
end
try
    w
catch e
    println(e)
end


UndefVarError(:w)


In [36]:
const e = 2.71828182845904523536 # Define Constant

2.718281828459045

## Types (Julia Type System)

In [37]:
println((1 + 2)::Int) # Type Assertion

3


In [38]:
# x::Float64 = 10 # Type Declaration (Script-Only)
function sinc(x)::Float64
    x == 0 && return 1
    return sin(π * x)/(π * x)
end

sinc (generic function with 1 method)

In [39]:
abstract type MyAbstractType end
abstract type MySubAbstractType <: MyAbstractType end
 # (AbstractFloat, Integer, Irrational, Rational) <: Real <: Number <: Any
 # (BigFloat, Float16, Float32, Float64) <: AbstractFloat
 # (BigInt, Bool, Signed, Unsigned) <: Integer
 # (Int8, Int16, Int32, Int64) <: Signed ('UInt' -> Unsigned)

In [40]:
primitive type MyPrimitiveType <: MyAbstractType 64 end
struct Point # Composite Type
    x::Real
    y::Real
end
point = Point(1, 2) # Constructor
println(fieldnames(Point)) # Field Names List
println((point.x, point.y)) # Access Field Values

(:x, :y)
(1, 2)


In [41]:
mutable struct MutablePoint # Mutable Struct
    x::Real
    y::Real
end
point = MutablePoint(1, 2)
point.x = 2

2

In [42]:
Union{Int, AbstractString} # Type Union (Abstract)
struct ParametricPoint{T} # Parametric Composite Type
    x::T
    y::T
end
point = ParametricPoint{Int}(1, 2)

ParametricPoint{Int64}(1, 2)

In [43]:
Array{Float64}; Array{Real}
 # Array{Float64}: Contiguous Memory Block
 # Array{Real}: Pointer Array

Array{Real, N} where N

In [44]:
function pnorm(point::ParametricPoint{<:Real}) # Accept Subtypes
    sqrt(point.x^2 + point.y^2)
end
struct Rational{T<:Integer} <: Real
    num::T
    den::T
end

In [86]:
typeof((1, 1.0)); Tuple{Int64, Float64} # Tuple Type
typeof((1, 2, 3)); NTuple{3, Int64} # Shorthand Notation
# NamedTuple{(:a, :b), Int64, Float64} # Named Tuple Type
ages = (andrew=20, ryan=16)
ages.ryan == ages[:ryan]
isa(Float64, Type{Float64}) # Singleton Type

true

In [46]:
ParametricPoint{Int} <: ParametricPoint # UnionAll Type
 # ParametricPoint <-> ParametricPoint{T} where T
function pnorm(p::ParametricPoint{T}) where T<:Real
    sqrt(p.x^2 + p.y^2)
end

pnorm (generic function with 1 method)

In [47]:
 # Type Variable Bounds: Array{T} where Int<:T<:Number
 # Shorthand Notation: Array{<:Integer} <-> Array{T} where T<:Integer
 # Vector: const Vector = Array{T,1} where T | Vector{T} = Array{T,1}
# const Int = Int64 # Type Alias (64-Bit)
isa(1.0, Float64); typeof(DataType); supertype(Float64); subtypes(Real);

In [48]:
struct Polar{T<:Real} <: Number
    r::T
    Θ::T
end
Polar(r::Real, Θ::Real) = Polar(promote(r, Θ)...)
Base.show(io::IO, z::Polar) = print(io, z.r, " * exp(", z.Θ, "im)")
println(Polar(5.2, π/2))

5.2 * exp(1.5707963267948966im)


## Methods (Multiple Dispatch)

In [49]:
# Multiple Dispatch: Inspect All Function Arguments -> Invoke Method
 # Java: method(this, args...) has implicit first argument: this
 # Python: method(self, args...) has explicit first argument: self
 # => Single Dispatch: obj.method(args...) -> method(obj, args...)

In [50]:
f(x::Float64, y::Float64) = 2x + y
# f(1, 2) # Invalid Arguments
f(x::Number, y::Number) = 2x + y
f(1, 2.0) # Method Selection
methods(f) # Method Signatures

# 4 methods for generic function "f":
[1] f(x::Float64, y::Float64) in Main at In[50]:1
[2] f(x::Number, y::Number) in Main at In[50]:3
[3] f(x) in Main at In[32]:7
[4] f(x, y) in Main at In[14]:4

In [85]:
h(x::Float64, y) = 2x + y
h(x, y::Float64) = 2x + y
h(1.0, 2.0) # Method Ambiguity

MethodError(h, (1.0, 2.0), 0x000000000000741b)


In [52]:
same_type(x::T, y::T) where {T} = true # Parametric Method
same_type(x, y) = false
# append(v::Vector{T}, x::T) where {T} = [v..., x]
# typeof(x::T) where {T} = T

same_type (generic function with 2 methods)

In [53]:
 # For 1 Argument:  where {T} == where T (Optional {})
 # For 2 Arguments: where {T, S} == where S where T (Nested)
#  getindex(A::AbstractArray{T, N}, indexes::Vararg{Number, N}) where {T, N} = A[indexes...]

getindex (generic function with 1 method)

In [54]:
struct Polynomial{R}
    coeffs::Vector{R}
end
function (poly::Polynomial)(x) # Functor (Ex: Constructor)
    polyval = poly.coeffs[1]
    for i = 2:length(poly.coeffs)
        polyval += poly.coeffs[i] * x^(i - 1)
    end
    return polyval
end
poly = Polynomial([1, 10, 100])
poly(3)

931

In [55]:
Point(x) = Point(x, 0) # Outer Constructor
struct OrderedPair # Inner Constructor
    x::Real
    y::Real
    OrderedPair(x, y) = x > y ? error("Constraint: x <= y") : new(x, y)
end

In [56]:
mutable struct SelfReferential
    obj::SelfReferential
    SelfReferential() = (x = new(); x.obj = x)
end

In [57]:
struct ConstructPoint{T<:Real} # Parametric Constructor
    x::T
    y::T
    ConstructPoint{T}(x, y) where {T<:Real} = new(x, y)
end
Point(x::T, y::T) where {T<:Real} = Point{T}(x, y)
Point(x::Real, y::Real) = Point(promote(x, y)...)

Point

## Conversion and Promotion

In [58]:
Int64(12.0) # convert(Int64, 12.0)
# Base.convert(::Type{Bool}, x::Real) = x == 0 ? false : x == 1 ? true : throw(InexactError())
promote(1, 2.5); promote(2.0, 3//4); promote(1 + 2im, 1.5)
# +(x::Number, y::Number) = +(promote(x, y)...)
# Base.promote_rule(::Type{Float64}, ::Type{Float32}) = Float64

(1.0 + 2.0im, 1.5 + 0.0im)

## Multi-Dimensional Arrays

In [59]:
A = Array{Int}(undef, 4) # Uninitialized Two-Dimensional Array

4-element Vector{Int64}:
 140082473374512
 140082396883376
 140082466311168
 140082405250944

In [60]:
using LinearAlgebra
zeros(Int, 2); ones(Int, 2) # Array Construction
B = Matrix(I, 2, 2) # 'Explicit' Identity Matrix
fill("Value", 2); fill!(A, 10) # Fill Array
rand(Int, 2) # Uniform Distribution

2-element Vector{Int64}:
  6023330182588278303
 -8220736074735307172

In [61]:
eltype(A); length(A); ndims(A); size(A)
reshape(A, (2, 2)) # Reshape Array (Modify Dimensions)

2×2 Matrix{Int64}:
 10  10
 10  10

In [62]:
B = copy(A); cat(A, B, dims=1) # Concatenate Along Specified Dimension
vcat(A, B); cat(A, B, dims=1); [A; B] # Vertical Concatenation
hcat(A, B); cat(A, B, dims=2); [A B] # Horizontal Concatenation
transpose(A); adjoint(A); A' # [Conjugate] Transpose

1×4 adjoint(::Vector{Int64}) with eltype Int64:
 10  10  10  10

In [63]:
Int[1, 2, 3, 4] # Initialize Typed Array

4-element Vector{Int64}:
 1
 2
 3
 4

In [64]:
squares = [i^2 for i = 1:10] # Comprehension
squares = (i^2 for i = 1:10) # Generator (No Memory Allocation)
println(sum(squares)) # Memory Allocated On-Demand
even_squares = (i^2 for i = 1:10 if i % 2 == 0) # Filtering

Base.Generator{UnitRange{Int64}, var"#14#15"}(var"#14#15"(), 1:10)


Base.Generator{Base.Iterators.Filter{var"#17#19", UnitRange{Int64}}, var"#16#18"}(var"#16#18"(), Base.Iterators.Filter{var"#17#19", UnitRange{Int64}}(var"#17#19"(), 1:10))

In [65]:
getindex(A, 1); A[1] # Array Indexing
setindex!(A, 10, 1); A[1] = 10 # Array Assignment
C = [1 2; 3 4]; println(C[2, :]) # Array Splicing
for (index, value) in enumerate(A) # Enumeration
    println("A[$index] = $value")
end

[3, 4]
A[1] = 10
A[2] = 10
A[3] = 10
A[4] = 10


In [66]:
# push!(); pop!(); insert!(); splice!() # List Operations
# union(); intersect(); setdiff(); issubset() # Set Operations {∪, ∩, ⊆}
# issubset(); in() # Subset Operations {⊆, ⊈, ⊇, ⊉}, Set Member {∈}

## Interfaces (Iteration)

In [67]:
# function Base.iterate(iterable, state=(iterable.start, 0))
#     element, index = state
#     index >= iterable.length && return nothing
#     return (element, (f(element), index + 1))
# end
# function Base.iterate(iterable, (el, i)=(iterable.start, 0))
#     return i >= iterable.length ? nothing : (el, (f(el), i + 1))
# end

In [68]:
struct Squares
    count::Int
end
function Base.iterate(iterable::Squares, state=1)
	return state > iterable.count ? nothing : (state^2, state + 1)
end
Base.eltype(iterable::Squares) = Int
Base.length(iterable::Squares) = iterable.count
foreach(println, Squares(7))
println(25 in Squares(10))

1
4
9
16
25
36
49
true


In [69]:
let iterable = Squares(7), next = iterate(iterable)
    while next !== nothing
        el, state = next
        println(el) # Body
        next = iterate(iterable, state)
    end
end

1
4
9
16
25
36
49


In [70]:
collect(Squares(10)) # Collection -> Array

10-element Vector{Int64}:
   1
   4
   9
  16
  25
  36
  49
  64
  81
 100

In [71]:
Base.sum(S::Squares) = (n = S.count; return n * (n + 1) * (2n + 1) / 6)
sum(Squares(1803))

Squares(1803)

In [72]:
function Base.getindex(S::Squares, i::Int)
    1 <= i <= S.count || throw(BoundsError(S, i))
    return i^2
end
println(Squares(100)[25])
Base.firstindex(S::Squares) = 1
Base.lastindex(S::Squares) = length(S)
println(Squares(100)[end])

625
10000


## Modules (Variable Workspaces)

In [73]:
 # Julia Load Path: push!(LOAD_PATH, "/Path/To/My/Module/")
 # Julia Startup File: ~/.julia/config/startup.jl
module Coord2D
import Base.convert
export Cartesian, Polar
struct Cartesian{T<:Real}
    x::T
    y::T
end
struct Polar{T<:Real}
    r::T # Radius
    θ::T # Angle {Degrees}
end
convert(::Type{Cartesian}, P::Polar) = Cartesian(P.r * cosd(P.θ), P.r * sind(P.θ))
convert(::Type{Polar}, P::Cartesian) = Polar(sqrt(P.x^2 + P.y^2), atand(P.y / P.x))
end

Main.Coord2D